# Generated by Django 3.2.7 on 2021-11-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='isApplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enroll',
            name='isHired',
            field=models.BooleanField(default=False),
        ),
    ]
