# Generated by Django 3.2.7 on 2021-11-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20211111_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enroll',
        ),
    ]
