# Generated by Django 3.2.7 on 2021-10-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='marksObtained',
        ),
        migrations.AlterField(
            model_name='education',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='education',
            name='img',
            field=models.ImageField(default=None, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('S', 'School'), ('C', 'College'), ('U', 'University')], default=None, max_length=1),
        ),
    ]
