# Generated by Django 3.2.7 on 2021-10-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0002_auto_20211029_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='file',
            field=models.FileField(default=None, upload_to='file/'),
        ),
    ]
