# Generated by Django 3.2.7 on 2021-10-29 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0003_auto_20211029_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='file',
        ),
    ]
