# Generated by Django 3.2.7 on 2021-11-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUser', '0005_education_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='file',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
